# -*- coding: utf-8 -*-
"""UTS KSI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100EHoZ0KHKkXPKpGdlzTgJXL3CbEZfry

# DEEP TRANSFER LEARNING
Pengklasifikasian hewan kucing atau anjing atau bukan keduanya
"""

#Import library yang dibutuhkan
from keras.applications.efficientnet_v2 import EfficientNetV2M
from keras.applications.mobilenet_v2 import MobileNetV2

#Deklarasikan model yang akan dipakai
model = EfficientNetV2M()
#model = MobileNetV2()

#Tampilkan layer-layer model VGG16
model.summary()

import requests
import numpy as np
import cv2
import matplotlib.pyplot as plt
from PIL import Image

urls=[]

urls.append("https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2021/08/20065849/Ini-X-Gangguan-Kesehatan-yang-Umumnya-Dialami-Anjing-Golden.jpg")
urls.append("https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/other/cat_relaxing_on_patio_other/1800x1200_cat_relaxing_on_patio_other.jpg")
urls.append("https://wallpaperaccess.com/full/3396763.jpg")

imgs=[]
plt.figure(figsize=(15,6))
for u in range(0,len(urls)):
  r = requests.get(urls[u], stream=True) #Download
  img = np.array(Image.open(r.raw))  #Konversi ke NP Array
  plt.subplot(1,len(urls),u+1) #Menampilkan ke matplotlib
  plt.imshow(img) #Menampilkan ke matplotlib
  img = cv2.resize(img, (480,480)) #Resize sesuai input VGG 16
  imgs.append(img) #Kumpulkan semua image yang telah di preproses ke imgs
plt.show() #Menampilkan ke matplotlib
imgs = np.array(imgs) #Konversi ke Np Array 
print (imgs.shape) #Debuging (Apakah shape-nya benar?)

"""VGG 16 memiliki target 1000 kelas 
https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a

Kelas anjing: 151 (Chihuahua) - 268 (Mexican hairless)

Kelas kucing: 281 (tabby cat) - 287 (lynx) 


"""

yh = model.predict(imgs)
for i in range(len(urls)):
  if(np.argmax(yh[i]) >= 151 and np.argmax(yh[i])<=268 ): #rentang kelas anjing antara 151-268 pada VGG 16
      print("Anjing")
  elif(np.argmax(yh[i]) >= 281 and np.argmax(yh[i])<=287 ) : #rentang kelas kucing antara 151-268 pada VGG 16
      print("Kucing")
  else:
      print("Bukan Anjing atau Kucing")

yh.shape

yh[0]

np.argmax(yh[1])

